# 
# Configuration for the Appveyor continuous integration system.
# 

# === Test Matrix ===

platform:
  - x86
  - x64

configuration: Release

# === Build Steps ===

build_script:
  - ps: .\appveyor-build.ps1
